services:
  reverse-proxy:
    image: traefik:v2.11
    command:
      - --api.dashboard=true  # Enables Traefik Dashboard
      - --api.insecure=true   # Allows dashboard access without authentication
      - --providers.docker
      - --entrypoints.http.address=:80
      - --entrypoints.mysql.address=:3306
      - --providers.docker.exposedbydefault=true
    ports:
      - "80:80"
      - "8080:8080"
      - "3306:3306"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: course_catalog
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - ./database/volume:/var/lib/mysql
    hostname: database.cc.localhost
    labels:
      - traefik.tcp.routers.mysql.entrypoints=mysql
      - traefik.tcp.routers.mysql.rule=HostSNI(`*`)
      - traefik.tcp.services.mysql.loadbalancer.server.port=3306
    ports:
      - 8001:3306

  api:
    #image: php:8.3-apache
    build:
      context: ./api
      dockerfile:
        Dockerfile
    container_name: api
    depends_on:
      - db
    volumes:
      - ./api/:/var/www/html/
      - ./api/apache.conf:/etc/apache2/sites-available/000-default.conf  # Mount custom Apache config
    stdin_open: true
    tty: true
    hostname: api.cc.localhost
    labels:
      - traefik.http.routers.api.rule=Host(`api.cc.localhost`)
    entrypoint: ["/bin/bash", "/var/www/html/entrypoint.sh"]

  front:
    image: php:8.3-apache
    container_name: front
    depends_on:
      - api
    volumes:
      - ./front_end/:/var/www/html/
      - ./front_end/apache.conf:/etc/apache2/sites-available/000-default.conf  # Mount custom Apache config
    stdin_open: true
    tty: true
    hostname: cc.localhost
    labels:
      - traefik.http.routers.front.rule=Host(`cc.localhost`)